---
development:
  API_HOST: http://localhost:9090
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/dev.db

test:
  APP_HOST: http://localhost:9090
  # Infrastructure  
  DB_FILENAME: app/infrastructure/database/local/test.db

app_test:
  API_HOST: http://localhost:9090
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  # Application
  APP_HOST: http://localhost:9292

production:
  API_HOST: https://mlbatbat-api.herokuapp.com