---
# Name the file secrets.yml

development:
  SESSION_SECRET: <SECRET>
  REDIS_URL: <URL on heroku Config vars>

test:
  SESSION_SECRET: <SECRET>
  REDIS_URL: <URL on heroku Config vars>

production:
  SESSION_SECRET: <SECRET>
  REDIS_URL: <URL on heroku Config vars>