---
# Name the file secrets.yml

development:
  SESSION_SECRET: <SECRET>
  REDIS_URL: <URL on heroku Config vars>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  SCHEDULE_QUEUE: codepraise-clone-development
  SCHEDULE_QUEUE_URL: <set by AWS>

test:
  SESSION_SECRET: <SECRET>
  REDIS_URL: <URL on heroku Config vars>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  SCHEDULE_QUEUE: codepraise-clone-development
  SCHEDULE_QUEUE_URL: <set by AWS>

production:
  SESSION_SECRET: <SECRET>
  REDIS_URL: <URL on heroku Config vars>
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  SCHEDULE_QUEUE: codepraise-clone-development
  SCHEDULE_QUEUE_URL: <set by AWS>